RGB_MATRIX_ENABLE = yes
RGB_MATRIX_SPLIT = yes
SPLIT_KEYBOARD = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
POINTING_DEVICE_INVERT_X = yes  # КРИТИЧЕСКОЕ ИЗМЕНЕНИЕ: добавлено "= yes"
RGB_MATRIX_KEYPRESSES = yes
RGB_MATRIX_FRAMEBUFFER_EFFECTS = yes
