SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT = i2c
SPLIT_LAYER_STATE_ENABLE = yes
SPLIT_LED_STATE_ENABLE = yes
SPLIT_MODS_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_LED_COUNT = 58

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
